name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Add react-router-dom if missing
        run: |
          if ! npm list react-router-dom > /dev/null 2>&1; then
            npm install react-router-dom
          fi

      - name: Commit updated package files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json package-lock.json
          git commit -m "Auto-install react-router-dom"
          git push
        continue-on-error: true
